services:
  monitor:
    image: ghcr.io/911218sky/gmail-monitor:latest
    env_file: .env
    volumes:
      - ./stock_data.json:/app/stock_data.json
      - ./subscribers.json:/app/subscribers.json
      - ./config.json:/app/config.json
      - ./admins.json:/app/admins.json
    restart: unless-stopped
